pub const VOXEL_GRID_SLOT_SIZE = 1024;
pub const VOXEL_GRID_SLOT_COUNT = 4 * 1024;
pub const VOXEL_GRID_BUFFER_SIZE = VOXEL_GRID_SLOT_COUNT * VOXEL_GRID_SLOT_SIZE;

pub const MAX_SPAN_SIZE_EXPONENT = 6;
