const zgpu = @import("zgpu");
const wgpu = zgpu.wgpu;
const zmath = @import("zmath");

const TextureDescriptor = @import("../types.zig").TextureDescriptor;
const BindGroup = @import("../bind_group.zig").BindGroup;

// Generated by this script:
//
// ```js
// // Algo from https://gist.github.com/ncruces/b4ee29d37d2ea88a8775acb56a7a6975
// function hammersley(n, bias) {
//   if (isNaN(bias)) bias = (1-n)/(n+n);

//   function phi2(n) {
//     let r = 0;
//     let b = n.toString(2);
//     for (let i = 0; i < b.length; ++i) {
//       if (Number(b[i])) r += 1/(1 << b.length-i);
//     }
//     return r;
//   }

//   let r = [];
//   for (let i = 0; i < n; i++) {
//     r.push([i/n+bias, phi2(i)+bias]);
//   }
//   return r;
// }

// function mix(a, b, t) {
//     return a + (b - a) * t;
// }

// const LEN = 16;

// const SSAO_KERNEL = hammersley(LEN + 1, 0).slice(1).map(([x,y], i) => {
//     const phi = 2.0 * Math.PI * x;
//     const z = y;
//     const r = Math.sqrt(1.0 - z * z);

//     const scale = mix(0.1, 1.0, (i / LEN) ** 2);

//     return [
//         r * Math.cos(phi) * scale,
//         r * Math.sin(phi) * scale,
//         z * scale,
//     ];
// });

// console.log(JSON.stringify(SSAO_KERNEL, null, 2));
// ```

const SSAO_KERNEL = [_]@Vector(3, f32){
    .{ 0.0807544638987683, 0.031284445982349245, 0.05 },
    .{ 0.07406980915136845, 0.06752355294802097, 0.02587890625 },
    .{ 0.03362884267995751, 0.06753582030294031, 0.08554687500000001 },
    .{ 0.012050998216944735, 0.13005098229642853, 0.016455078125 },
    .{ -0.03337939111788825, 0.1173163909457521, 0.09765625 },
    .{ -0.10496646170900802, 0.13899805897934506, 0.070458984375 },
    .{ -0.09325530020789846, 0.05774123729709625, 0.1982421875 },
    .{ -0.26710655945638095, 0.04993086944244573, 0.0170166015625 },
    .{ -0.2641338341717875, -0.0493751707790531, 0.18281250000000002 },
    .{ -0.3107507075754225, -0.1924086921210007, 0.1202392578125 },
    .{ -0.15863959830904056, -0.21007277832560564, 0.36689453125 },
    .{ -0.14122997453305156, -0.4963718735030745, 0.0985107421875 },
    .{ 0.04062107871043934, -0.4383712529975416, 0.41679687499999996 },
    .{ 0.2782227630380755, -0.55874663031225, 0.30368652343749997 },
    .{ 0.2029186420041959, -0.1849847842797866, 0.73974609375 },
    .{ 0.8304415400137206, -0.3217147665375614, 0.02784423828125 },
};

// `@Vector(3, f32)` is 16 bytes (instead of 12), because of alignment.
// 16 bytes alignment is matching the WGSL `vec3f` alignment.
const SSAO_KERNEL_SIZE = SSAO_KERNEL.len * @sizeOf(@Vector(3, f32));

pub const PostEffectShaderRuntimeSettings = packed struct {
    ssao_enabled: bool,
    debug_ssao_enabled: bool,

    _padding: u30 = 0,
};

pub const FinalPassBindGroupLayout = struct {
    bind_group_layout_handle: zgpu.BindGroupLayoutHandle,
    ssao_sampling_kernel_buffer_handle: zgpu.BufferHandle,

    pub fn init(gctx: *zgpu.GraphicsContext) FinalPassBindGroupLayout {
        const ssao_sampling_kernel_buffer_handle = gctx.createBuffer(.{
            .usage = .{
                .copy_dst = true,
                .storage = true,
            },
            .size = SSAO_KERNEL_SIZE,
        });
        const gpu_buffer = gctx.lookupResource(ssao_sampling_kernel_buffer_handle) orelse @panic("Can't create SSAO sampling kernel buffer");
        gctx.queue.writeBuffer(gpu_buffer, 0, @Vector(3, f32), &SSAO_KERNEL);

        const bind_group_layout_handle = gctx.createBindGroupLayout(&.{
            // depth texture
            zgpu.textureEntry(
                0,
                .{ .fragment = true },
                .unfilterable_float, // or .depth
                .tvdim_2d,
                false,
            ),
            // color texture
            zgpu.textureEntry(
                1,
                .{ .fragment = true },
                .float,
                .tvdim_2d,
                false,
            ),
            // normal texture
            zgpu.textureEntry(
                2,
                .{ .fragment = true },
                .float,
                .tvdim_2d,
                false,
            ),
            // color sampler
            zgpu.samplerEntry(
                3,
                .{ .fragment = true },
                .filtering, // TODO: Maybe it's better to have non_filtering for texture -> texture transformations?
            ),
            // depth sampler (depth texture has UnfilterableFloat type)
            zgpu.samplerEntry(
                4,
                .{ .fragment = true },
                .non_filtering,
            ),
            // view to clip matrix
            zgpu.bufferEntry(
                5,
                .{ .fragment = true },
                .uniform,
                true,
                0,
            ),
            // clip to view matrix
            zgpu.bufferEntry(
                6,
                .{ .fragment = true },
                .uniform,
                true,
                0,
            ),
            // settings
            zgpu.bufferEntry(
                7,
                .{ .fragment = true },
                .uniform,
                true,
                0,
            ),
            // SSAO sampling kernel
            zgpu.bufferEntry(
                8,
                .{ .fragment = true },
                .read_only_storage,
                false,
                0,
            ),
        });

        return .{
            .bind_group_layout_handle = bind_group_layout_handle,
            .ssao_sampling_kernel_buffer_handle = ssao_sampling_kernel_buffer_handle,
        };
    }

    pub fn deinit(bind_group_layout: FinalPassBindGroupLayout, gctx: *zgpu.GraphicsContext) void {
        gctx.releaseResource(bind_group_layout.bind_group_layout_handle);
        gctx.releaseResource(bind_group_layout.ssao_sampling_kernel_buffer_handle);
    }

    pub fn createBindGroup(
        bind_group_layout: FinalPassBindGroupLayout,
        gctx: *zgpu.GraphicsContext,
        sampler: zgpu.SamplerHandle,
        depth_texture_view_handle: zgpu.TextureViewHandle,
        color_texture_view_handle: zgpu.TextureViewHandle,
        normal_texture_view_handle: zgpu.TextureViewHandle,
    ) BindGroup {
        const bind_group_handle = gctx.createBindGroup(
            bind_group_layout.bind_group_layout_handle,
            &.{
                // depth texture
                .{
                    .binding = 0,
                    .texture_view_handle = depth_texture_view_handle,
                },

                // color texture
                .{
                    .binding = 1,
                    .texture_view_handle = color_texture_view_handle,
                },

                // normal texture
                .{
                    .binding = 2,
                    .texture_view_handle = normal_texture_view_handle,
                },

                // color sampler
                .{
                    .binding = 3,
                    .sampler_handle = sampler,
                },

                // depth sampler
                .{
                    .binding = 4,
                    .sampler_handle = sampler,
                },

                // view to clip matrix
                .{
                    .binding = 5,
                    .buffer_handle = gctx.uniforms.buffer,
                    .offset = 0,
                    .size = @sizeOf(zmath.Mat),
                },

                // clip to view matrix
                .{
                    .binding = 6,
                    .buffer_handle = gctx.uniforms.buffer,
                    .offset = 0,
                    .size = @sizeOf(zmath.Mat),
                },

                // settings
                .{
                    .binding = 7,
                    .buffer_handle = gctx.uniforms.buffer,
                    .offset = 0,
                    .size = @sizeOf(PostEffectShaderRuntimeSettings),
                },

                // SSAO sampling kernel
                .{
                    .binding = 8,
                    .buffer_handle = bind_group_layout.ssao_sampling_kernel_buffer_handle,
                    .offset = 0,
                    .size = SSAO_KERNEL_SIZE,
                },
            },
        );

        return .{
            .wgpu_bind_group = gctx.lookupResource(bind_group_handle).?,
            .bind_group_handle = bind_group_handle,
        };
    }
};
